### ISSUE TITLE
Error scanning Scala code in IntelliJ

### ISSUE THREAD

**Issue by jaxley** [find-sec-bugs/find-sec-bugs#112]
I dropped the latest 1.4.3 jar in the current Findbugs-IDEA plugin version of findbugs (FindBugs-IDEA-0.9.997).

1. Files scanned drops precipitously (21 using 1.4.1; 5 using 1.4.3)
1. This exception shows up in the Event Log:  11:07:02 AM AssertionError: Out of bounds mutables in static main.AuthNState$.()V (show balloon)

I'm scanning Scala code as a test.

**Comment by h3xstream** [comment]
@jaxley Can you provide a sample from `main.AuthNState`? You can offuscate the code as you need.
Without this test case, it will be hard to reproduce.

Note : You are part of the first users for Scala.

**Comment by jaxley** [comment]
Happy to be an early adopter ;-)

The error does not occur until I define the Boolean method that does the comparison.  Here's similar code that reproduces the error:

```scala
package main2

import main2.AuthNState2.AuthNState2

class Foo {
  var AuthenticationStatus2:AuthenticationStatus2 = new AuthenticationStatus2()

  def isAuthenticated: Boolean = {
    AuthenticationStatus2.state == AuthNState2.Authenticated
  }
}

class AuthenticationStatus2 {
  // attribute bucket for the current state
  var attributes:Map[String, AnyRef] = Map()

  // state
  var state:AuthNState2 = AuthNState2.Unknown
}

object AuthNState2 extends Enumeration {
  type AuthNState2 = Value
  val Unknown, Authenticated = Value
}
```

I also didn't notice there was a stacktrace available for the bug:

```
Out of bounds mutables in static main.AuthNState$.<clinit>()V
java.lang.AssertionError: Out of bounds mutables in static main.AuthNState$.<clinit>()V
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.transferTaintToMutables(TaintFrameModelingVisitor.java:389)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.visitInvoke(TaintFrameModelingVisitor.java:273)
	at com.h3xstream.findsecbugs.taintanalysis.TaintFrameModelingVisitor.visitINVOKESPECIAL(TaintFrameModelingVisitor.java:198)
	at org.apache.bcel.generic.INVOKESPECIAL.accept(INVOKESPECIAL.java:80)
	at edu.umd.cs.findbugs.ba.AbstractFrameModelingVisitor.analyzeInstruction(AbstractFrameModelingVisitor.java:84)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.transferInstruction(TaintAnalysis.java:65)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.transferInstruction(TaintAnalysis.java:38)
	at edu.umd.cs.findbugs.ba.AbstractDataflowAnalysis.transfer(AbstractDataflowAnalysis.java:135)
	at edu.umd.cs.findbugs.ba.Dataflow.execute(Dataflow.java:376)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:67)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:36)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
	at com.h3xstream.findsecbugs.injection.TaintDetector.getTaintDataFlow(TaintDetector.java:243)
	at com.h3xstream.findsecbugs.injection.TaintDetector.analyzeMethod(TaintDetector.java:99)
	at com.h3xstream.findsecbugs.injection.TaintDetector.visitClassContext(TaintDetector.java:88)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:167)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:58)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$1.run(FindBugsStarter.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by formanek** [comment]
@jaxley It's just an assertion for developers to detect something, which I've thought should never happen, you can get rid of it by switching the assertions off and the analysis should continue normally :) Scala probably produces some code, which Java can't (or it is very uncommon). Unfortunately, I cannot program in Scala, so I would need a bytecode of the problematic code to debug it. Easiest solution from my side is removal of this assertion and hope everything will be ok then.

**Comment by h3xstream** [comment]
@formanek I have a simple test to reproduce the problem. "com/h3xstream/findsecbugs/crypto/SslDisablerDetectorTest.java".

you can find the actual bytecode here : `find-sec-bugs/plugin/src/test/resources/bytecode_samples/ssl_disabler_scala.jar``

My current fix is available at commit 9614dfcf25f4858e80263ed24f62bbf5948be5d7

**Comment by h3xstream** [comment]
@jaxley The [version 1.4.5](http://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/1.4.5/findsecbugs-plugin-1.4.5.jar) was release. Let me know in the comment if the problem still occurs.

Also, I am slowly adding some Scala specific rules. If you have ideas, you can add them here : #111 (Scala mini planning).

**Comment by jaxley** [comment]
Great news!  I'll give that a try in the coming weeks.
