### ISSUE TITLE
Test failure : Invalid VNA after location

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#192]
JstlOutDetectorWeblogicTest is failing. It seems to be related to the bytecode structure.

```
Tests run: 169, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 66.941 sec <<< FAILURE! - in TestSuite
jspEscape_weblogic(com.h3xstream.findsecbugs.jsp.JstlOutDetectorWeblogicTest)  Time elapsed: 0.503 sec  <<< FAILURE!
java.lang.AssertionError: Invalid VNA after location   97: aconst_null[1](1) in basic block 27 in jsp_servlet.__test._jsp__tag0(javax.servlet.ServletRequest, javax.servlet.ServletResponse, javax.servlet.jsp.PageContext, javax.servlet.jsp.tagext.JspTag, javax.servlet.jsp.tagext.JspTag)
        at edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.transferInstruction(IsNullValueAnalysis.java:360)
        at edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.transferInstruction(IsNullValueAnalysis.java:72)
        at edu.umd.cs.findbugs.ba.AbstractDataflowAnalysis.transfer(AbstractDataflowAnalysis.java:135)
        at edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.transfer(IsNullValueAnalysis.java:282)
        at edu.umd.cs.findbugs.ba.npe.IsNullValueAnalysis.transfer(IsNullValueAnalysis.java:72)
        at edu.umd.cs.findbugs.ba.AbstractDataflowAnalysis.getFactAtLocation(AbstractDataflowAnalysis.java:84)
        at edu.umd.cs.findbugs.ba.Dataflow.getFactAtLocation(Dataflow.java:501)
        at edu.umd.cs.findbugs.detect.LoadOfKnownNullValue.analyzeMethod(LoadOfKnownNullValue.java:129)
        at edu.umd.cs.findbugs.detect.LoadOfKnownNullValue.visitClassContext(LoadOfKnownNullValue.java:62)
        at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
        at com.h3xstream.findbugs.test.service.FindBugsLauncher.analyze(FindBugsLauncher.java:131)
        at com.h3xstream.findbugs.test.service.FindBugsLauncher.analyze(FindBugsLauncher.java:68)
        at com.h3xstream.findbugs.test.BaseDetectorTest.analyze(BaseDetectorTest.java:58)
        at com.h3xstream.findsecbugs.jsp.JstlOutDetectorWeblogicTest.jspEscape_weblogic(JstlOutDetectorWeblogicTest.java:43)


Results :

Failed tests:
  JstlOutDetectorWeblogicTest.jspEscape_weblogic:43->BaseDetectorTest.analyze:58 Invalid VNA after location   97: aconst_null[1](1) in basic block 27 in jsp_servlet.__test._jsp__tag0(javax.servlet.ServletRequest, javax.servlet.ServletResponse, javax.servlet.jsp.PageContext, javax.servlet.jsp.tagext.JspTag, javax.servlet.jsp.tagext.JspTag)
```

**Comment by formanek** [comment]
All tests are passing on my machine and even Travis CI is green for my recent pull request :)

**Comment by h3xstream** [comment]
@formanek 
It seems that the problem was cause by unsafe iteration in BadHexadecimalConversionDetector.
https://github.com/find-sec-bugs/find-sec-bugs/commit/6827e92555de301c3d02dde268fb67dff31c29c7#diff-69602855c0071701d3989ac68f5c8fbfL78

I accidentally commit that change which was unrelated to the Custom Injection detector.
