### ISSUE TITLE
Failed when build find-sec-bugs myself

### ISSUE THREAD

**Issue by eumenide** [find-sec-bugs/find-sec-bugs#379]
I meet the similar problem as [issue#140](https://github.com/find-sec-bugs/find-sec-bugs/issues/140).

What I do is a git clone, and then run: "mvn clean install" to build something. But when I do that for find-sec-bugs I get the following errors. I tried the various options described under /Compiling, like running "mvn clean" first, then "mvn clean install", or running: "mvn clean test-compile", and both the clean and test-compile options are successed, but the install option generates errors like those below.

Can you help me solve this problem?

Thanks, Eumes.

```  command
[INFO]
[ERROR] Tests run: 252, Failures: 30, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Find Security Bugs root 1.8.0 ...................... SUCCESS [  1.090 s]
[INFO] FindBugs Test Utility .............................. SUCCESS [  3.320 s]
[INFO] Find Security Bugs plugin dependencies ............. SUCCESS [14:36 min]
[INFO] Find Security Bugs Plugin .......................... FAILURE [05:52 min]
[INFO] Find Security Bugs Graph Builder Plugin 1.8.0 ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:34 min
[INFO] Finished at: 2018-04-02T23:10:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project findsecbugs-plugin: There are test failures.
[ERROR]
[ERROR] Please refer to D:\testSpace\find-sec-bugs\plugin\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
```

And the below is the version of my maven and JDK.
``` command
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T03:49:05+08:00)
Maven home: D:\softwares\maven\apache-maven-3.5.3\bin\..
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_151\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by h3xstream** [comment]
These are tests failures. Can you show the tests classes failing?

These should show up just before:
```
[INFO]
[ERROR] Tests run: 252, Failures: 30, Errors: 0, Skipped: 0
```

**Comment by eumenide** [comment]
One of these failing tests is like below:

```command
[ERROR]   XssServletDetectorTest.detectXssServlet_safeEncoders:95 
Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet3",methodName="writeWithEncoders",lineNumber=<24>
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_safeEncoders(XssServletDetectorTest.java:95)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)
```

Thanks!

**Comment by eumenide** [comment]
And all the 30 failures are the follow:

```command
[ERROR] detectBadKeySize(com.h3xstream.findsecbugs.crypto.InsufficientKeySizeRsaDetectorTest)  Time elapsed: 0.379 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="RSA_KEY_SIZE",className="InsufficientKeySizeRsa",lineNumber=<14>
);
-> at com.h3xstream.findsecbugs.crypto.InsufficientKeySizeRsaDetectorTest.detectBadKeySize(InsufficientKeySizeRsaDetectorTest.java:44)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECRKS: RSA usage with short key
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.crypto.InsufficientKeySizeRsaDetectorTest.detectBadKeySize(InsufficientKeySizeRsaDetectorTest.java:44)

[ERROR] detectResponseSplitting(com.h3xstream.findsecbugs.HttpResponseSplittingDetectorTest)  Time elapsed: 0.216 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="HTTP_RESPONSE_SPLITTING",className="ResponseSplittingServlet",methodName="doGet",lineNumber=<15>
);
-> at com.h3xstream.findsecbugs.HttpResponseSplittingDetectorTest.detectResponseSplitting(HttpResponseSplittingDetectorTest.java:39)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.HttpResponseSplittingDetectorTest.detectResponseSplitting(HttpResponseSplittingDetectorTest.java:39)

[ERROR] detectCommandInjection(com.h3xstream.findsecbugs.injection.command.CommandInjectionDetectorTest)  Time elapsed: 0.571 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="COMMAND_INJECTION",className="CommandInjection",lineNumber=<44>
);
-> at com.h3xstream.findsecbugs.injection.command.CommandInjectionDetectorTest.detectCommandInjection(CommandInjectionDetectorTest.java:54)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.injection.command.CommandInjectionDetectorTest.detectCommandInjection(CommandInjectionDetectorTest.java:54)

[ERROR] detectTaintedAndInjection(com.h3xstream.findsecbugs.injection.script.OgnlInjectionDetectorTest)  Time elapsed: 0.193 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="OGNL_INJECTION",className="StrutsTaintedApi",lineNumber=<10>
);
-> at com.h3xstream.findsecbugs.injection.script.OgnlInjectionDetectorTest.detectTaintedAndInjection(OgnlInjectionDetectorTest.java:190)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECOGNL: Potential code injection when using OGNL expression
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.injection.script.OgnlInjectionDetectorTest.detectTaintedAndInjection(OgnlInjectionDetectorTest.java:190)

[ERROR] detectSmtpInjection(com.h3xstream.findsecbugs.injection.smtp.SmtpHeaderInjectionDetectorTest)  Time elapsed: 0.238 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="SMTP_HEADER_INJECTION",className="SmtpClient",lineNumber=<52>
);
-> at com.h3xstream.findsecbugs.injection.smtp.SmtpHeaderInjectionDetectorTest.detectSmtpInjection(SmtpHeaderInjectionDetectorTest.java:64)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.injection.smtp.SmtpHeaderInjectionDetectorTest.detectSmtpInjection(SmtpHeaderInjectionDetectorTest.java:64)

[ERROR] detectTBV(com.h3xstream.findsecbugs.injection.trust.TrustBoundaryViolationDetectorTest)  Time elapsed: 0.162 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="TRUST_BOUNDARY_VIOLATION",className="TrustBoundaryViolation",methodName="setSessionAttributeNameTainted",
);
-> at com.h3xstream.findsecbugs.injection.trust.TrustBoundaryViolationDetectorTest.detectTBV(TrustBoundaryViolationDetectorTest.java:43)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.injection.trust.TrustBoundaryViolationDetectorTest.detectTBV(TrustBoundaryViolationDetectorTest.java:43)

[ERROR] jspEscape3_safe(com.h3xstream.findsecbugs.jsp.JstlOutDetectorTest)  Time elapsed: 0.189 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="JSP_JSTL_OUT",
);
-> at com.h3xstream.findsecbugs.jsp.JstlOutDetectorTest.jspEscape3_safe(JstlOutDetectorTest.java:73)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECJSPJSTL: Escaping of special XML characters is disabled
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.jsp.JstlOutDetectorTest.jspEscape3_safe(JstlOutDetectorTest.java:73)

[ERROR] jspEscape4_unknown(com.h3xstream.findsecbugs.jsp.JstlOutDetectorTest)  Time elapsed: 0.178 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="JSP_JSTL_OUT",
);
-> at com.h3xstream.findsecbugs.jsp.JstlOutDetectorTest.jspEscape4_unknown(JstlOutDetectorTest.java:99)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECJSPJSTL: Escaping of special XML characters is disabled
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.jsp.JstlOutDetectorTest.jspEscape4_unknown(JstlOutDetectorTest.java:99)

[ERROR] jspEscape_weblogic(com.h3xstream.findsecbugs.jsp.JstlOutDetectorWeblogicTest)  Time elapsed: 0.426 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="JSP_JSTL_OUT",className="__test",lineNumber=<210>
);
-> at com.h3xstream.findsecbugs.jsp.JstlOutDetectorWeblogicTest.jspEscape_weblogic(JstlOutDetectorWeblogicTest.java:47)
Actual invocation has different arguments:
securityReporter.doReportBug(
    RCN: Redundant nullcheck of value known to be null
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.jsp.JstlOutDetectorWeblogicTest.jspEscape_weblogic(JstlOutDetectorWeblogicTest.java:47)

[ERROR] detectCommonsCollectionGadget(com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest)  Time elapsed: 0.2 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="DESERIALIZATION_GADGET",className="InvokerTransformer",
);
-> at com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest.detectCommonsCollectionGadget(DeserializationGadgetDetectorTest.java:42)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECDESGAD: This class could be used as deserialization gadget
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest.detectCommonsCollectionGadget(DeserializationGadgetDetectorTest.java:42)

[ERROR] detectGroovyGadget(com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest)  Time elapsed: 0.185 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="DESERIALIZATION_GADGET",className="ConvertedClosure",
);
-> at com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest.detectGroovyGadget(DeserializationGadgetDetectorTest.java:62)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECDESGAD: This class could be used as deserialization gadget
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest.detectGroovyGadget(DeserializationGadgetDetectorTest.java:62)

[ERROR] detectSpringGadget(com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest)  Time elapsed: 0.218 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="DESERIALIZATION_GADGET",className="MethodInvokeTypeProvider",
);
-> at com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest.detectSpringGadget(DeserializationGadgetDetectorTest.java:87)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECDESGAD: This class could be used as deserialization gadget
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.serial.DeserializationGadgetDetectorTest.detectSpringGadget(DeserializationGadgetDetectorTest.java:87)

[ERROR] testSafeTestCases(com.h3xstream.findsecbugs.taintanalysis.JaxRsAnnotatedControllerTest)  Time elapsed: 0.172 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="SQL_INJECTION_HIBERNATE",className="JaxRsAnnotatedController",methodName="getInfoUser",
);
-> at com.h3xstream.findsecbugs.taintanalysis.JaxRsAnnotatedControllerTest.testSafeTestCases(JaxRsAnnotatedControllerTest.java:40)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECJRS: Found JAX-RS REST endpoint
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.taintanalysis.JaxRsAnnotatedControllerTest.testSafeTestCases(JaxRsAnnotatedControllerTest.java:40)

[ERROR] testSafeTestCases(com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest)  Time elapsed: 0.179 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="SQL_INJECTION_HIBERNATE",
);
-> at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest.testSafeTestCases(TaintAnalysisTaintedByAnnotationTest.java:49)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSQLIHIB: Potential SQL/HQL Injection (Hibernate)
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest.testSafeTestCases(TaintAnalysisTaintedByAnnotationTest.java:49)

[ERROR] testUnsafeTestCases(com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest)  Time elapsed: 0.228 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="SQL_INJECTION_HIBERNATE",
);
-> at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest.testUnsafeTestCases(TaintAnalysisTaintedByAnnotationTest.java:73)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSQLIHIB: Potential SQL/HQL Injection (Hibernate)
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest.testUnsafeTestCases(TaintAnalysisTaintedByAnnotationTest.java:73)

[ERROR] testVariousTaintedAnnotations(com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest)  Time elapsed: 0.146 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="SQL_INJECTION_HIBERNATE",methodName="requestParam",
);
-> at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest.testVariousTaintedAnnotations(TaintAnalysisTaintedByAnnotationTest.java:99)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSQLIHIB: Potential SQL/HQL Injection (Hibernate)
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysisTaintedByAnnotationTest.testVariousTaintedAnnotations(TaintAnalysisTaintedByAnnotationTest.java:99)

[ERROR] allSignatures(com.h3xstream.findsecbugs.template.FreemarkerDetectorTest)  Time elapsed: 0.209 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="TEMPLATE_INJECTION_FREEMARKER",className="FreemarkerUsage",methodName="allSignatures",lineNumber=<57>
);
-> at com.h3xstream.findsecbugs.template.FreemarkerDetectorTest.allSignatures(FreemarkerDetectorTest.java:70)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECFREEM: Potential template injection with Freemarker
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.template.FreemarkerDetectorTest.allSignatures(FreemarkerDetectorTest.java:70)

[ERROR] basicUsagesTesting(com.h3xstream.findsecbugs.template.FreemarkerDetectorTest)  Time elapsed: 0.185 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="TEMPLATE_INJECTION_FREEMARKER",className="FreemarkerUsage",methodName="simple",lineNumber=<42>
);
-> at com.h3xstream.findsecbugs.template.FreemarkerDetectorTest.basicUsagesTesting(FreemarkerDetectorTest.java:44)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECFREEM: Potential template injection with Freemarker
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.template.FreemarkerDetectorTest.basicUsagesTesting(FreemarkerDetectorTest.java:44)

[ERROR] allSignatures(com.h3xstream.findsecbugs.template.VelocityDetectorTest)  Time elapsed: 0.187 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="TEMPLATE_INJECTION_VELOCITY",className="VelocityUsage",methodName="allSignatures",lineNumber=<37>
);
-> at com.h3xstream.findsecbugs.template.VelocityDetectorTest.allSignatures(VelocityDetectorTest.java:71)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECVELO: Potential template injection with Velocity
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.template.VelocityDetectorTest.allSignatures(VelocityDetectorTest.java:71)

[ERROR] basicUsagesTesting(com.h3xstream.findsecbugs.template.VelocityDetectorTest)  Time elapsed: 0.199 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="TEMPLATE_INJECTION_VELOCITY",className="VelocityUsage",methodName="usage1",lineNumber=<27>
);
-> at com.h3xstream.findsecbugs.template.VelocityDetectorTest.basicUsagesTesting(VelocityDetectorTest.java:45)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECVELO: Potential template injection with Velocity
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.template.VelocityDetectorTest.basicUsagesTesting(VelocityDetectorTest.java:45)

[ERROR] detectUnvalidatedRedirect(com.h3xstream.findsecbugs.UnvalidatedRedirectDetectorTest)  Time elapsed: 0.168 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="UNVALIDATED_REDIRECT",className="UnvalidatedRedirectServlet",methodName="unvalidatedRedirect1",
);
-> at com.h3xstream.findsecbugs.UnvalidatedRedirectDetectorTest.detectUnvalidatedRedirect(UnvalidatedRedirectDetectorTest.java:40)
Actual invocation has different arguments:
securityReporter.doReportBug(
    RCN: Redundant nullcheck of value known to be non-null
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.UnvalidatedRedirectDetectorTest.detectUnvalidatedRedirect(UnvalidatedRedirectDetectorTest.java:40)

[ERROR] detectXssDirectUse(com.h3xstream.findsecbugs.xss.JspXssDetectorTest)  Time elapsed: 0.18 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_JSP_PRINT",
);
-> at com.h3xstream.findsecbugs.xss.JspXssDetectorTest.detectXssDirectUse(JspXssDetectorTest.java:69)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECXSS1: Potential XSS in JSP
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.JspXssDetectorTest.detectXssDirectUse(JspXssDetectorTest.java:69)

[ERROR] detectXssMultipleTransfertLocal(com.h3xstream.findsecbugs.xss.JspXssDetectorTest)  Time elapsed: 0.18 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_JSP_PRINT",
);
-> at com.h3xstream.findsecbugs.xss.JspXssDetectorTest.detectXssMultipleTransfertLocal(JspXssDetectorTest.java:164)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECXSS1: Potential XSS in JSP
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.JspXssDetectorTest.detectXssMultipleTransfertLocal(JspXssDetectorTest.java:164)

[ERROR] detectXssTransferLocal(com.h3xstream.findsecbugs.xss.JspXssDetectorTest)  Time elapsed: 0.191 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_JSP_PRINT",
);
-> at com.h3xstream.findsecbugs.xss.JspXssDetectorTest.detectXssTransferLocal(JspXssDetectorTest.java:103)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECXSS1: Potential XSS in JSP
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.JspXssDetectorTest.detectXssTransferLocal(JspXssDetectorTest.java:103)

[ERROR] detectXssServlet1(com.h3xstream.findsecbugs.xss.XssServletDetectorTest)  Time elapsed: 0.224 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet1",methodName="doGet",lineNumber=<17>
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet1(XssServletDetectorTest.java:54)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet1(XssServletDetectorTest.java:54)

[ERROR] detectXssServlet6(com.h3xstream.findsecbugs.xss.XssServletDetectorTest)  Time elapsed: 0.164 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet6",methodName="doPost",
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet6(XssServletDetectorTest.java:170)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSH: HTTP headers untrusted
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet6(XssServletDetectorTest.java:170)

[ERROR] detectXssServlet7(com.h3xstream.findsecbugs.xss.XssServletDetectorTest)  Time elapsed: 0.168 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet7",methodName="doPost",lineNumber=<32>
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet7(XssServletDetectorTest.java:200)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECFUN: Tainted filename read
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet7(XssServletDetectorTest.java:200)

[ERROR] detectXssServlet_basicTaintAnalysis(com.h3xstream.findsecbugs.xss.XssServletDetectorTest)  Time elapsed: 0.144 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet4",methodName="writeWithStringBuilder",
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_basicTaintAnalysis(XssServletDetectorTest.java:118)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_basicTaintAnalysis(XssServletDetectorTest.java:118)

[ERROR] detectXssServlet_safeEncoders(com.h3xstream.findsecbugs.xss.XssServletDetectorTest)  Time elapsed: 0.179 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet3",methodName="writeWithEncoders",lineNumber=<24>
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_safeEncoders(XssServletDetectorTest.java:95)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_safeEncoders(XssServletDetectorTest.java:95)

[ERROR] detectXssServlet_separateMethodBasic(com.h3xstream.findsecbugs.xss.XssServletDetectorTest)  Time elapsed: 0.152 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet2",methodName="indirectWrite",
);
-> at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_separateMethodBasic(XssServletDetectorTest.java:79)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:192)

	at com.h3xstream.findsecbugs.xss.XssServletDetectorTest.detectXssServlet_separateMethodBasic(XssServletDetectorTest.java:79)
```

**Comment by nemozqqz** [comment]
Tests failures still happen to me. The test code wants somthing like 
```java
securityReporter.doReportBug(
    BugInstance with:
bugType="XSS_SERVLET",className="XssServlet3",methodName="writeWithEncoders",lineNumber=<24>
);
```
But actual invocation has different arguments:
```Java
securityReporter.doReportBug(
    SECSP: Untrusted servlet parameter
);
```
The actual argument is BugInstance.toString, while the expected is members of BugInstance.

I did some debugging, and found a NullPointerException in the test code.
The test [code](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/test/java/com/h3xstream/findsecbugs/xss/XssServletDetectorTest.java#L57):
```java
verify(reporter).doReportBug(bugDefinition().bugType("XSS_SERVLET").inClass("XssServlet1").inMethod("doGet").withPriority("Low").atLine(19).build());
````
`doReportBug` accepts a `BugInstance`, and the [build()](https://github.com/find-sec-bugs/find-sec-bugs/blob/99814871f33ca0484b975f2fe51bae2bc1bcf40a/findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/matcher/BugInstanceMatcherBuilder.java#L132) function here is 
```java
 return Matchers.argThat(new BugInstanceMatcher(bugType, className, methodName, fieldName, lineNumber, lineNumberApprox, priority, jspFile, multipleChoicesLine,unknownSources));
```
According to mockito [doc](https://static.javadoc.io/org.mockito/mockito-core/1.10.19/org/mockito/Matchers.html#argThat(org.hamcrest.Matcher)), `Matchers.argThat` returns Null, thus `verify(reporter).doReportBug()` has a Null argument and it is not handled.

Hope this helps to found out the reason of mismatch.

**Comment by h3xstream** [comment]
Sorry for the late response, this is not an easy one to solve.

Looking back at it.. I can see that your default encoding is GBK (Chinese characters).
```
Default locale: zh_CN, platform encoding: GBK
```
There might be part of the code from SpotBugs that rely on the default encoding (bad practice).
