### ISSUE TITLE
Crash with spotbugs 3.1.4

### ISSUE THREAD

**Issue by xanderhades** [find-sec-bugs/find-sec-bugs#406]
Hi,
since spotbugs 3.1.4, find-sec-bugs does not work for me anymore.

Stack trace :
```
Exception in thread "main" java.lang.NoSuchMethodError: edu.umd.cs.findbugs.io.IO.close(Ljava/io/Closeable;)V
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.loadFileContent(TaintAnalysis.java:274)
	at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.<clinit>(TaintAnalysis.java:57)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:168)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:52)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.getTaintDataFlow(AbstractTaintDetector.java:123)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.analyzeMethod(AbstractTaintDetector.java:91)
	at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.visitClassContext(AbstractTaintDetector.java:76)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
```

If I revert to spotbugs 3.1.3, analysis is done correctly.

I can provide code sample privately, but it seems like it crashes on any project for me.

Thanks!

**Comment by pzygielo** [comment]
Please see https://github.com/spotbugs/spotbugs/issues/661.

**Comment by xanderhades** [comment]
Thank you, I will close this issue.
