### ISSUE TITLE
Unsupported class file major version 56

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#512]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Java               |  12   |
| SpotBugs           | 3.1.5  |
| FindSecBugs        |  1.9.0   |

## Problem

FindSecBugs CLI use an old version of SpotBugs and is not supporting recent bytecode. (Java 12)

Error: 

```
2 analysis passes to performException in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 56
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:158)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:146)
	at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
	at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
	at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:877)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:223)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
```

**Comment by TidDl3R** [comment]
I also met this mistake, how should we solve it?

**Comment by h3xstream** [comment]
@TidDl3R An old version was package with the CLI.
The Gradle script that generate the release for the CLI package was update.

You can get the repackage here : 
https://github.com/find-sec-bugs/find-sec-bugs/releases/tag/version-1.9.0

It does not include the fixes from the version 1.10.0. I will do a new release in the next two weeks.

**Comment by hiteshgargavid** [comment]
Still facing the same issue on MAC OS with the latest releases

**Comment by hiteshgargavid** [comment]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
Scanning archives (1 / 1)
2 analysis passes to performException in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
	at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
	at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:877)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:223)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
