### ISSUE TITLE
"Error: missing bug code for keySECEMA " in FindSecBugs 1.10.0

### ISSUE THREAD

**Issue by efeat** [find-sec-bugs/find-sec-bugs#526]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | 3.6.0   |
| Java               | 1.8.0_111   |
| SpotBugs           |   3.1.12.2  |
| FindSecBugs        | 1.10.0 |

## Problem

Since the last find security bug update on October 17th, 2019, the spotbugs analyze fails with the following error:

````
[INFO] --- spotbugs-maven-plugin:3.1.12.2:spotbugs (spotbugs) @ quipux-web ---
[INFO] Fork Value is true
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Error: missing bug code for keySECEMA
     [java] 	at edu.umd.cs.findbugs.DetectorFactoryCollection.getBugCode(DetectorFactoryCollection.java:506)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeBugCodes(SortedBugCollection.java:665)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeEpilogue(SortedBugCollection.java:569)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeXML(SortedBugCollection.java:548)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeXML(SortedBugCollection.java:457)
     [java] 	at edu.umd.cs.findbugs.XMLBugReporter.finish(XMLBugReporter.java:47)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1126)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
[INFO] ------------------------------------------------------------------------
````

It's fixed (while waiting the bug fix) by forcing the ` finsecbugs-plugin` version to 1.9.0:

```
				<groupId>com.github.spotbugs</groupId>
				<artifactId>spotbugs-maven-plugin</artifactId>
				<configuration>
					<effort>Max</effort>
					<threshold>Low</threshold>
					<failOnError>false</failOnError>
					<htmlOutput>true</htmlOutput>
					<xmlOutput>false</xmlOutput>
					<includeFilterFile>${parent.asset}/security-assets/spotbugs-security-include.xml</includeFilterFile>
					<excludeFilterFile>${parent.asset}/security-assets/spotbugs-security-exclude.xml</excludeFilterFile>
					<plugins>
						<plugin>
							<groupId>com.h3xstream.findsecbugs</groupId>
							<artifactId>findsecbugs-plugin</artifactId>
							<version>1.9.0</version> 
						</plugin>
					</plugins>
				</configuration>
```

**Comment by h3xstream** [comment]
I have release a new version on maven central. I will test it when it become available.

**Comment by h3xstream** [comment]
I have test the fix on WebGoat. It should work well on Maven.

Let me know if it work on your side.

```xml
<groupId>com.github.spotbugs</groupId>
<artifactId>spotbugs-maven-plugin</artifactId>
<configuration>
    <effort>Max</effort>
    <threshold>Low</threshold>
    <failOnError>false</failOnError>
    <htmlOutput>true</htmlOutput>
    <xmlOutput>false</xmlOutput>
    <includeFilterFile>${parent.asset}/security-assets/spotbugs-security-include.xml</includeFilterFile>
    <excludeFilterFile>${parent.asset}/security-assets/spotbugs-security- 
    <plugins>
        <plugin>
            <groupId>com.h3xstream.findsecbugs</groupId>
            <artifactId>findsecbugs-plugin</artifactId>
            <version>1.10.1</version> 
        </plugin>
    </plugins>
</configuration>
```

**Comment by efeat** [comment]
FIXED for me :)

Thanks
