### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by hktalent** [find-sec-bugs/find-sec-bugs#554]
$ wc -l ../listJars.txt
    1401 ../listJars.txt

$ cat ../listJars.txt|./findsecbugs.sh -xargs -progress -html -output report.htm
.....
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.IdentityHashMap.resize(IdentityHashMap.java:472)
        at java.util.IdentityHashMap.put(IdentityHashMap.java:441)
        at edu.umd.cs.findbugs.ba.BasicAbstractDataflowAnalysis.lookupOrCreateFact(BasicAbstractDataflowAnalysis.java:186)
        at edu.umd.cs.findbugs.ba.BasicAbstractDataflowAnalysis.getStartFact(BasicAbstractDataflowAnalysis.java:70)
        at edu.umd.cs.findbugs.ba.Dataflow.execute(Dataflow.java:234)
        at edu.umd.cs.findbugs.classfile.engine.bcel.ValueNumberDataflowFactory.analyze(ValueNumberDataflowFactory.java:76)
        at edu.umd.cs.findbugs.classfile.engine.bcel.ValueNumberDataflowFactory.analyze(ValueNumberDataflowFactory.java:46)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
        at edu.umd.cs.findbugs.ba.ClassContext.getMethodAnalysis(ClassContext.java:1005)
        at edu.umd.cs.findbugs.ba.ClassContext.getValueNumberDataflow(ClassContext.java:336)
        at edu.umd.cs.findbugs.detect.FindSelfComparison2.analyzeMethod(FindSelfComparison2.java:99)
        at edu.umd.cs.findbugs.detect.FindSelfComparison2.visitClassContext(FindSelfComparison2.java:74)
        at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
        at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
        at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
        at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
```

**Comment by hktalent** [comment]
I change 
vi findsecbugs.sh

java **-Xmx2000m -XX:+UseParallelGC** -cp "$LIBS" edu.umd.cs.findbugs.LaunchAppropriateUI -quiet -pluginList "$FINDBUGS_PLUGIN" -include "$DIR"/include.xml $@

see:
https://www.educative.io/edpresso/how-to-resolve-the-gc-overhead-limit-exceeded-error-in-java
