### ISSUE TITLE
Missing commons-codec library

### ISSUE THREAD

**Issue by skirge** [find-sec-bugs/find-sec-bugs#602]
## Environment

| Component          | Version |
| ------------------ | ------- |
| SpotBugs           | github   |
| FindSecBugs        | github   |

## Problem

Stacktrace during start of analysis when Spotbugs is run from command line:

```
Exception in thread "main" java.lang.RuntimeException: Could not instantiate com.h3xstream.findsecbugs.password.ConstantPasswordDetector as Detector
	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector(DetectorFactory.java:85)
	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector2(DetectorFactory.java:103)
	at edu.umd.cs.findbugs.DetectorFactory.createDetector2(DetectorFactory.java:396)
	at edu.umd.cs.findbugs.plan.AnalysisPass.instantiateDetector2sInPass(AnalysisPass.java:132)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1024)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at edu.umd.cs.findbugs.DetectorFactory$ReflectionDetectorCreator.createDetector(DetectorFactory.java:79)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/codec/Charsets
	at com.h3xstream.findsecbugs.password.ConstantPasswordDetector.getReader(ConstantPasswordDetector.java:386)
	at com.h3xstream.findsecbugs.password.ConstantPasswordDetector.loadMap(ConstantPasswordDetector.java:358)
	at com.h3xstream.findsecbugs.password.ConstantPasswordDetector.<init>(ConstantPasswordDetector.java:83)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.Charsets
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 16 more
```

it can be resolved by adding classpath entry manually:

CLASSPATH=/opt/spotbugs/lib/commons-codec-1.15.jar

**Comment by hiteshgargavid** [comment]
I am also facing the same issue but the commons-codec jar, where is it present exactly ?

**Comment by h3xstream** [comment]
This bug was pretty simple to fix. The following import is causing the issue.
```
import org.apache.commons.codec.Charsets;
```
The import is possible because we are compiling against SpotBugs 3.0 which has commons-codec. It is later drop in SpotBugs 4.0.
