### ISSUE TITLE
Not able to run findSecBugs via CLI on macOS

### ISSUE THREAD

**Issue by hiteshgargavid** [find-sec-bugs/find-sec-bugs#606]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
Scanning archives (1 / 1)
2 analysis passes to performException in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
	at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
	at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
	at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:877)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:223)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)

**Comment by h3xstream** [comment]
This error means you are scanning Java 14 code.
ASM used in this version of SpotBugs is not supporting it.
I will do a release this month. I will need to see if the latest SpotBugs version supports it.
