### ISSUE TITLE
Travis-CI is not executing on the PR

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#642]
## Environment

Travis-CI on the main repository.

## Problem

I received an alert from Travis-CI that the build was failing. It was however related to the build failing on my personal repository.

I notice after that Travis-CI is no longer part of the build check on GitHub. Only CodeQL is part of those checks.

## Error message

```
[ERROR] Tests run: 331, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 340.667 s <<< FAILURE! - in TestSuite
[ERROR] detectNormalizationAfterValidation(com.h3xstream.findsecbugs.NormalizeBeforeValidationTest)  Time elapsed: 0.39 s  <<< FAILURE!
org.mockito.exceptions.verification.ArgumentsAreDifferent: 

Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="NORMALIZE_BEFORE_VALIDATION",className="NormalizeAfter",methodName="validate",lineNumber=<19>
);
-> at com.h3xstream.findsecbugs.NormalizeBeforeValidationTest.detectNormalizationAfterValidation(NormalizeBeforeValidationTest.java:41)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECUNI: Improper handling of Unicode transformations
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:194)

	at com.h3xstream.findsecbugs.NormalizeBeforeValidationTest.detectNormalizationAfterValidation(NormalizeBeforeValidationTest.java:41)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   NormalizeBeforeValidationTest.detectNormalizationAfterValidation:41 
Argument(s) are different! Wanted:
securityReporter.doReportBug(
    BugInstance with:
bugType="NORMALIZE_BEFORE_VALIDATION",className="NormalizeAfter",methodName="validate",lineNumber=<19>
);
-> at com.h3xstream.findsecbugs.NormalizeBeforeValidationTest.detectNormalizationAfterValidation(NormalizeBeforeValidationTest.java:41)
Actual invocation has different arguments:
securityReporter.doReportBug(
    SECUNI: Improper handling of Unicode transformations
);
-> at edu.umd.cs.findbugs.AbstractBugReporter.reportBug(AbstractBugReporter.java:194)

[INFO] 
[ERROR] Tests run: 331, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OWASP Find Security Bugs root 1.12.0-SNAPSHOT:
[INFO] 
[INFO] OWASP Find Security Bugs root ...................... SUCCESS [  4.874 s]
[INFO] FindSecBugs Test Utility ........................... SUCCESS [ 10.680 s]
[INFO] Find Security Bugs Samples Dependencies ............ SUCCESS [  2.280 s]
[INFO] Find Security Bugs Samples Kotlin .................. SUCCESS [ 13.062 s]
[INFO] Find Security Bugs Samples Java .................... SUCCESS [  4.316 s]
[INFO] Find Security Bugs Samples JSP ..................... SUCCESS [  8.156 s]
[INFO] OWASP Find Security Bugs Plugin .................... FAILURE [05:47 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:31 min
[INFO] Finished at: 2021-06-21T19:40:59Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project findsecbugs-plugin: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/h3xstream/find-sec-bugs/findsecbugs-plugin/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :findsecbugs-plugin
travis_time:end:00369010:start=1624304067184930537,finish=1624304459479025536,duration=392294094999,event=script
[0K[31;1mThe command "mvn clean test -Pjacoco -Ptravisci -B -V" exited with 1.[0m
```

**Comment by h3xstream** [comment]
From the quick investigation. The fact that the build was only effective on h3xstream/find-sec-bugs and no longer on find-sec-bugs/find-sec-bugs is due to some progressive migration from the past year.
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

The travis-ci.org was stopped completly in mid-june 2021. It is now read-only. Some repository were migrate to .com automatically.

**Comment by h3xstream** [comment]
At the moment, Github action are used instead for tests. The need to run CI tasks on Travis is less of a priority.
