### ISSUE TITLE
Tests fail with OpenJDK version newer than 12.x

### ISSUE THREAD

**Issue by baloghadamsoftware** [find-sec-bugs/find-sec-bugs#656]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | 3.8.2   |
| Java               | >=13.0.8   |

## Problem

After executing mvn clean, then mvn compile and finally mvn test, then using OpenJDK version 13.x I get test failure for almost all the tests.

For version 13.x-15.x I get an exception for almost every test file:

```
|ERROR| EasyBugReporter : Unsupported class file major version 59
java.lang.IllegalArgumentException: Unsupported class file major version 59
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
        at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
        at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
        at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
        at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
        at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
        at edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:774)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:220)
        at com.h3xstream.findbugs.test.service.FindBugsLauncher.analyze(FindBugsLauncher.java:139)
        at com.h3xstream.findbugs.test.BaseDetectorTest.analyze(BaseDetectorTest.java:80)
        at com.h3xstream.findsecbugs.injection.custom.CustomInjectionDetectorTest.detectInjection(CustomInjectionDetectorTest.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at org.testng.TestRunner.privateRun(TestRunner.java:782)
        at org.testng.TestRunner.run(TestRunner.java:632)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
        at org.testng.SuiteRunner.run(SuiteRunner.java:268)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
        at org.testng.TestNG.run(TestNG.java:1064)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

For version 16.x-17.0 I do not get exception but the test fails with this message:
[ERROR] detectInjection(com.h3xstream.findsecbugs.injection.custom.CustomInjectionDetectorTest)  Time elapsed: 0.732 s  <<< FAILURE!
java.lang.ExceptionInInitializerError
        at com.h3xstream.findsecbugs.injection.custom.CustomInjectionDetectorTest.detectInjection(CustomInjectionDetectorTest.java:52)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2a48d10f
        at com.h3xstream.findsecbugs.injection.custom.CustomInjectionDetectorTest.detectInjection(CustomInjectionDetectorTest.java:52)
```

Do I do something wrong or are OpenJDK versions 13.x and above unsupported?

**Comment by h3xstream** [comment]
This will be supported when updating ASM package with SpotBugs.

**Comment by baloghadamsoftware** [comment]
> This will be supported when updating ASM package with SpotBugs.

Sorry, i  do not fully understand you. ASM version in SpotBugs is 9.2 which is the most current one.
