### ISSUE TITLE
missing bug code for keySECXXEVAL

### ISSUE THREAD

**Issue by skirge** [find-sec-bugs/find-sec-bugs#693]
Following error was thrown during my analysis:

missing bug code for keySECXXEVAL

I think short bug code is missing in messages.xml

```
<BugCode abbrev="SECXXEVAL">XML validation vulnerable to XXE</BugCode>
```

**Comment by pavelorehov** [comment]
I have same issue with last 1.13.0 version.

```
INFO spotbugs-maven-plugin:4.8.3.1:spotbugs (spotbugs)
INFO Fork Value is true
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Error: missing bug code for keySECXXEVAL
     [java] 	at edu.umd.cs.findbugs.DetectorFactoryCollection.getBugCode(DetectorFactoryCollection.java:509)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeBugCodes(SortedBugCollection.java:673)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeEpilogue(SortedBugCollection.java:579)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeXML(SortedBugCollection.java:558)
     [java] 	at edu.umd.cs.findbugs.SortedBugCollection.writeXML(SortedBugCollection.java:467)
     [java] 	at edu.umd.cs.findbugs.XMLBugReporter.finish(XMLBugReporter.java:47)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1165)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)

```

**Comment by Vampire** [comment]
Was also reported at #727 and fixed in #728.
There is "just" a release missing that includes the fix.

**Comment by kmoens** [comment]
When can we expect a release of this fix?

**Comment by gtoison** [comment]
The fix was released as part of 1.14.0
